### ISSUE TITLE
Usage with JWT

### ISSUE THREAD

**Issue by SvenLie** [DirectoryTree/LdapRecord-Lumen#2]
Is it possible to use LDAP authentication with JWT driver? When i configure my auth.php, i ran in a issue `Authentication user provider [ldap] is not defined.`

```php
<?php

return [
    'defaults' => [
        'guard' => 'api',
        'passwords' => 'users',
    ],

    'guards' => [
        'api' => [
            'driver' => 'jwt',
            'provider' => 'ldap',
        ],
    ],

    'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => \App\User::class
        ],
        'ldap' => [
            'driver' => 'ldap',
            'model' => \App\Ldap\Models\User::class,
            'database' => [
                'model' => App\User::class,
                'sync_passwords' => false,
                'sync_attributes' => [
                    'name' => 'displayname',
                    'username' => 'cn',
                    'email' => 'mail'
                ],
                'sync_existing' => [
                    'email' => 'mail'
                ]
            ],
        ],
    ]
];
```

**Comment by stevebauman** [comment]
Hi @SvenLie,

I’ve never implemented JWT in my own applications, but from what I understand, it should work with some modifications.

The error you posted is quite generic — it leads me to believe that LdapRecord-Laravel has not been installed.

Can you post your `composer.json` file?

**Comment by stevebauman** [comment]
Whoops — I just noticed you posted this on the Lumen repository. The authentication driver is not available on the Lumen repository because Laravel does not include the required authentication foundation inside of Lumen that LdapRecord-Laravel relies on, only barebones auth.

You will need to use Laravel for this purpose.

I hope this helps!
